language: cpp

compiler:
 - gcc
 - clang

before_script:
 - sudo apt-get install doxygen
 - sudo apt-get install graphviz
 - sudo apt-get install libxml2-dev
 - ./bootstrap

script: ./configure && make && make check